{{- if .Values.encryption.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gohookbridge.encryptionSecretName" . }}
  labels:
    {{- include "gohookbridge.labels" . | nindent 4 }}
type: Opaque
data:
  public_key: {{ .Values.encryption.publicKey | b64enc | quote }}
  private_key: {{ .Values.encryption.privateKey | b64enc | quote }}
{{- end }}