{{- if .Values.server.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gohookbridge.fullname" . }}-server
  labels:
    {{- include "gohookbridge.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.server.service.type }}
  ports:
  - name: http
    port: {{ .Values.server.service.port }}
    targetPort: {{ .Values.server.port }}
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "gohookbridge.name" . }}
    app.kubernetes.io/component: server
{{- end }}