FROM registry.access.redhat.com/ubi9/ubi-minimal
RUN microdnf -y update && microdnf -y --nodirs install tar rsync shadow-utils && microdnf clean all && useradd gohookbridge && rm -rf /var/cache/yum
COPY gohookbridge /usr/local/bin/gohookbridge
WORKDIR /home/gohookbridge
USER 1001
ENTRYPOINT ["/usr/local/bin/gohookbridge"]