// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type Image
func (r *Binding) AsImage() *Image { // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/main.go#L25)
	q := r.query.Select("asImage")

	return &Image{
		query: q,
	}
}

// Retrieve the binding value, as type ImageBuild
func (r *Binding) AsImageBuild() *ImageBuild { // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/build.go#L13)
	q := r.query.Select("asImageBuild")

	return &ImageBuild{
		query: q,
	}
}

// Create or update a binding of type ImageBuild in the environment
func (r *Env) WithImageBuildInput(name string, value *ImageBuild, description string) *Env { // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/build.go#L13)
	assertNotNil("value", value)
	q := r.query.Select("withImageBuildInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired ImageBuild output to be assigned in the environment
func (r *Env) WithImageBuildOutput(name string, description string) *Env { // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/build.go#L13)
	q := r.query.Select("withImageBuildOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type Image in the environment
func (r *Env) WithImageInput(name string, value *Image, description string) *Env { // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/main.go#L25)
	assertNotNil("value", value)
	q := r.query.Select("withImageInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Image output to be assigned in the environment
func (r *Env) WithImageOutput(name string, description string) *Env { // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/main.go#L25)
	q := r.query.Select("withImageOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

type Image struct { // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/main.go#L25)
	query *querybuilder.Selection

	id   *ID
	lint *string
}
type WithImageFunc func(r *Image) *Image

// With calls the provided function with current Image.
//
// This is useful for reusability and readability by not breaking the calling chain.
func (r *Image) With(f WithImageFunc) *Image {
	return f(r)
}

func (r *Image) WithGraphQLQuery(q *querybuilder.Selection) *Image {
	return &Image{
		query: q,
	}
}

// ImageBuildOpts contains options for Image.Build
type ImageBuildOpts struct {
	//
	// The dockerfile path
	//
	//
	// Default: "Dockerfile"
	Dockerfile string // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/main.go#L109)
	//
	// Set extra directories
	//
	WithDirectories []*Directory // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/main.go#L113)
}

// Build permit to build image from Dockerfile
func (r *Image) Build(source *Directory, opts ...ImageBuildOpts) *ImageBuild { // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/main.go#L101)
	assertNotNil("source", source)
	q := r.query.Select("build")
	for i := len(opts) - 1; i >= 0; i-- {
		// `dockerfile` optional argument
		if !querybuilder.IsZeroValue(opts[i].Dockerfile) {
			q = q.Arg("dockerfile", opts[i].Dockerfile)
		}
		// `withDirectories` optional argument
		if !querybuilder.IsZeroValue(opts[i].WithDirectories) {
			q = q.Arg("withDirectories", opts[i].WithDirectories)
		}
	}
	q = q.Arg("source", source)

	return &ImageBuild{
		query: q,
	}
}

// ImageCiOpts contains options for Image.Ci
type ImageCiOpts struct {
	//
	// Dockerfile path
	//
	//
	// Default: "Dockerfile"
	Dockerfile string // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/pipeline.go#L28)
	//
	// Run in ci: push the image to the registry
	//
	Ci bool // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/pipeline.go#L32)
	//
	// The registry server
	//
	Registry string // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/pipeline.go#L36)
	//
	// The repository name
	//
	RepositoryName string // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/pipeline.go#L40)
	//
	// The image version to publish
	//
	Version string // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/pipeline.go#L44)
	//
	// The registry username
	//
	RegistryUsername *Secret // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/pipeline.go#L48)
	//
	// The registry password
	//
	RegistryPassword *Secret // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/pipeline.go#L52)
	//
	// Dry-run: skip the push and its requirement checks even when ci is set
	//
	DryRun bool // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/pipeline.go#L56)
}

// Ci runs lint, build, and push (when enabled) as a single CI entrypoint.
func (r *Image) Ci(source *Directory, opts ...ImageCiOpts) *Directory { // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/pipeline.go#L18)
	assertNotNil("source", source)
	q := r.query.Select("ci")
	for i := len(opts) - 1; i >= 0; i-- {
		// `dockerfile` optional argument
		if !querybuilder.IsZeroValue(opts[i].Dockerfile) {
			q = q.Arg("dockerfile", opts[i].Dockerfile)
		}
		// `ci` optional argument
		if !querybuilder.IsZeroValue(opts[i].Ci) {
			q = q.Arg("ci", opts[i].Ci)
		}
		// `registry` optional argument
		if !querybuilder.IsZeroValue(opts[i].Registry) {
			q = q.Arg("registry", opts[i].Registry)
		}
		// `repositoryName` optional argument
		if !querybuilder.IsZeroValue(opts[i].RepositoryName) {
			q = q.Arg("repositoryName", opts[i].RepositoryName)
		}
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
		// `registryUsername` optional argument
		if !querybuilder.IsZeroValue(opts[i].RegistryUsername) {
			q = q.Arg("registryUsername", opts[i].RegistryUsername)
		}
		// `registryPassword` optional argument
		if !querybuilder.IsZeroValue(opts[i].RegistryPassword) {
			q = q.Arg("registryPassword", opts[i].RegistryPassword)
		}
		// `dryRun` optional argument
		if !querybuilder.IsZeroValue(opts[i].DryRun) {
			q = q.Arg("dryRun", opts[i].DryRun)
		}
	}
	q = q.Arg("source", source)

	return &Directory{
		query: q,
	}
}

// ImageGenerateCiOpts contains options for Image.GenerateCi
type ImageGenerateCiOpts struct {
	//
	// Dockerfile path to lint and build
	//
	//
	// Default: "Dockerfile"
	Dockerfile string // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/pipeline.go#L110)
	//
	// Branches that trigger the pipeline
	//
	//
	// Default: ["main"]
	Branches []string // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/pipeline.go#L115)
	//
	// Dagger CLI version to use in CI (empty = engine default)
	//
	DaggerVersion string // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/pipeline.go#L119)
	//
	// OCI registry URL where the image is pushed.
	// Required by the generated pipeline (it runs with --ci true).
	//
	Registry string // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/pipeline.go#L124)
	//
	// Repository path inside the registry.
	// Required when registry is set.
	//
	Repository string // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/pipeline.go#L129)
	//
	// Branch commits land here when running on a tag.
	//
	//
	// Default: "main"
	DefaultBranch string // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/pipeline.go#L134)
	//
	// Configurable dagger module reference.
	// Defaults to this module's current version (auto-detected).
	//
	ModuleRef string // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/pipeline.go#L139)
	//
	// GitHub: secret name for registry username (empty = github.actor).
	//
	RegistryUsernameKey string // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/pipeline.go#L143)
	//
	// GitHub: secret name for registry password (empty = GITHUB_TOKEN).
	//
	RegistryPasswordKey string // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/pipeline.go#L147)
	//
	// Jenkins: credential id for registry username/password.
	//
	RegistryCredential string // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/pipeline.go#L151)
	//
	// Jenkins: credential id for git token.
	//
	GitTokenCredential string // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/pipeline.go#L155)
	//
	// GitLab: CI/CD variable name for registry username.
	//
	RegistryUsernameVar string // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/pipeline.go#L159)
	//
	// GitLab: CI/CD variable name for registry password.
	//
	RegistryPasswordVar string // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/pipeline.go#L163)
	//
	// GitLab: CI/CD variable name for git token.
	//
	GitTokenVar string // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/pipeline.go#L167)
	//
	// Jenkins: dagger kubernetes token credential ID.
	// When set, the Jenkinsfile uses the daggerKubernetes shared library step.
	//
	DaggerKubernetesToken string // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/pipeline.go#L172)
	//
	// Jenkins: dagger kubernetes server URL.
	//
	DaggerKubernetesURL string // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/pipeline.go#L176)
	//
	// Force overwrite DAGGER.md even if it already exists in source.
	//
	ForceDaggerMd bool // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/pipeline.go#L180)
}

// GenerateCi generates CI pipeline files for the given CI system.
func (r *Image) GenerateCi(ci string, opts ...ImageGenerateCiOpts) *Directory { // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/pipeline.go#L100)
	q := r.query.Select("generateCi")
	for i := len(opts) - 1; i >= 0; i-- {
		// `dockerfile` optional argument
		if !querybuilder.IsZeroValue(opts[i].Dockerfile) {
			q = q.Arg("dockerfile", opts[i].Dockerfile)
		}
		// `branches` optional argument
		if !querybuilder.IsZeroValue(opts[i].Branches) {
			q = q.Arg("branches", opts[i].Branches)
		}
		// `daggerVersion` optional argument
		if !querybuilder.IsZeroValue(opts[i].DaggerVersion) {
			q = q.Arg("daggerVersion", opts[i].DaggerVersion)
		}
		// `registry` optional argument
		if !querybuilder.IsZeroValue(opts[i].Registry) {
			q = q.Arg("registry", opts[i].Registry)
		}
		// `repository` optional argument
		if !querybuilder.IsZeroValue(opts[i].Repository) {
			q = q.Arg("repository", opts[i].Repository)
		}
		// `defaultBranch` optional argument
		if !querybuilder.IsZeroValue(opts[i].DefaultBranch) {
			q = q.Arg("defaultBranch", opts[i].DefaultBranch)
		}
		// `moduleRef` optional argument
		if !querybuilder.IsZeroValue(opts[i].ModuleRef) {
			q = q.Arg("moduleRef", opts[i].ModuleRef)
		}
		// `registryUsernameKey` optional argument
		if !querybuilder.IsZeroValue(opts[i].RegistryUsernameKey) {
			q = q.Arg("registryUsernameKey", opts[i].RegistryUsernameKey)
		}
		// `registryPasswordKey` optional argument
		if !querybuilder.IsZeroValue(opts[i].RegistryPasswordKey) {
			q = q.Arg("registryPasswordKey", opts[i].RegistryPasswordKey)
		}
		// `registryCredential` optional argument
		if !querybuilder.IsZeroValue(opts[i].RegistryCredential) {
			q = q.Arg("registryCredential", opts[i].RegistryCredential)
		}
		// `gitTokenCredential` optional argument
		if !querybuilder.IsZeroValue(opts[i].GitTokenCredential) {
			q = q.Arg("gitTokenCredential", opts[i].GitTokenCredential)
		}
		// `registryUsernameVar` optional argument
		if !querybuilder.IsZeroValue(opts[i].RegistryUsernameVar) {
			q = q.Arg("registryUsernameVar", opts[i].RegistryUsernameVar)
		}
		// `registryPasswordVar` optional argument
		if !querybuilder.IsZeroValue(opts[i].RegistryPasswordVar) {
			q = q.Arg("registryPasswordVar", opts[i].RegistryPasswordVar)
		}
		// `gitTokenVar` optional argument
		if !querybuilder.IsZeroValue(opts[i].GitTokenVar) {
			q = q.Arg("gitTokenVar", opts[i].GitTokenVar)
		}
		// `daggerKubernetesToken` optional argument
		if !querybuilder.IsZeroValue(opts[i].DaggerKubernetesToken) {
			q = q.Arg("daggerKubernetesToken", opts[i].DaggerKubernetesToken)
		}
		// `daggerKubernetesUrl` optional argument
		if !querybuilder.IsZeroValue(opts[i].DaggerKubernetesURL) {
			q = q.Arg("daggerKubernetesUrl", opts[i].DaggerKubernetesURL)
		}
		// `forceDaggerMd` optional argument
		if !querybuilder.IsZeroValue(opts[i].ForceDaggerMd) {
			q = q.Arg("forceDaggerMd", opts[i].ForceDaggerMd)
		}
	}
	q = q.Arg("ci", ci)

	return &Directory{
		query: q,
	}
}

// GetBaseHadolintContainer return the default image for hadolint
func (r *Image) GetBaseHadolintContainer() *Container { // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/main.go#L62)
	q := r.query.Select("getBaseHadolintContainer")

	return &Container{
		query: q,
	}
}

// A unique identifier for this Image.
func (r *Image) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Image) XXX_GraphQLType() string {
	return "Image"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Image) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Image) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Image) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Image) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Image{query: selectNode(dag.query, id, "Image")}
	return nil
}

// ImageLintOpts contains options for Image.Lint
type ImageLintOpts struct {
	//
	// The dockerfile path
	//
	Dockerfile string // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/lint.go#L27)
	//
	// The failure threshold
	//
	Threshold string // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/lint.go#L31)
}

// Lint permit to lint dockerfile image
func (r *Image) Lint(ctx context.Context, source *Directory, opts ...ImageLintOpts) (string, error) { // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/lint.go#L19)
	assertNotNil("source", source)
	if r.lint != nil {
		return *r.lint, nil
	}
	q := r.query.Select("lint")
	for i := len(opts) - 1; i >= 0; i-- {
		// `dockerfile` optional argument
		if !querybuilder.IsZeroValue(opts[i].Dockerfile) {
			q = q.Arg("dockerfile", opts[i].Dockerfile)
		}
		// `threshold` optional argument
		if !querybuilder.IsZeroValue(opts[i].Threshold) {
			q = q.Arg("threshold", opts[i].Threshold)
		}
	}
	q = q.Arg("source", source)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// ImageWithBuildArgOpts contains options for Image.WithBuildArg
type ImageWithBuildArgOpts struct {
	//
	// The build arg value
	//
	Value string // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/main.go#L76)
	//
	// The build arg secret value
	//
	SecretValue *Secret // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/main.go#L80)
}

func (r *Image) WithBuildArg(name string, opts ...ImageWithBuildArgOpts) *Image { // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/main.go#L67)
	q := r.query.Select("withBuildArg")
	for i := len(opts) - 1; i >= 0; i-- {
		// `value` optional argument
		if !querybuilder.IsZeroValue(opts[i].Value) {
			q = q.Arg("value", opts[i].Value)
		}
		// `secretValue` optional argument
		if !querybuilder.IsZeroValue(opts[i].SecretValue) {
			q = q.Arg("secretValue", opts[i].SecretValue)
		}
	}
	q = q.Arg("name", name)

	return &Image{
		query: q,
	}
}

// AsNode returns this Image as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Image) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

type ImageBuild struct { // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/build.go#L13)
	query *querybuilder.Selection

	id   *ID
	push *string
}

func (r *ImageBuild) WithGraphQLQuery(q *querybuilder.Selection) *ImageBuild {
	return &ImageBuild{
		query: q,
	}
}

// GetContainer permit to get the container
func (r *ImageBuild) GetContainer() *Container { // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/build.go#L19)
	q := r.query.Select("getContainer")

	return &Container{
		query: q,
	}
}

// A unique identifier for this ImageBuild.
func (r *ImageBuild) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *ImageBuild) XXX_GraphQLType() string {
	return "ImageBuild"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *ImageBuild) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *ImageBuild) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *ImageBuild) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *ImageBuild) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = ImageBuild{query: selectNode(dag.query, id, "ImageBuild")}
	return nil
}

// ImageBuildPushOpts contains options for ImageBuild.Push
type ImageBuildPushOpts struct {
	//
	// The registry username
	//
	WithRegistryUsername *Secret // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/build.go#L35)
	//
	// The registry password
	//
	WithRegistryPassword *Secret // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/build.go#L39)
}

// Push permit to push image
func (r *ImageBuild) Push(ctx context.Context, repositoryName string, version string, registryUrl string, opts ...ImageBuildPushOpts) (string, error) { // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/build.go#L24)
	if r.push != nil {
		return *r.push, nil
	}
	q := r.query.Select("push")
	for i := len(opts) - 1; i >= 0; i-- {
		// `withRegistryUsername` optional argument
		if !querybuilder.IsZeroValue(opts[i].WithRegistryUsername) {
			q = q.Arg("withRegistryUsername", opts[i].WithRegistryUsername)
		}
		// `withRegistryPassword` optional argument
		if !querybuilder.IsZeroValue(opts[i].WithRegistryPassword) {
			q = q.Arg("withRegistryPassword", opts[i].WithRegistryPassword)
		}
	}
	q = q.Arg("repositoryName", repositoryName)
	q = q.Arg("version", version)
	q = q.Arg("registryUrl", registryUrl)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// AsNode returns this ImageBuild as a Node.
// This is a local type conversion — no GraphQL call.
func (r *ImageBuild) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// ImageOpts contains options for Query.Image
type ImageOpts struct {
	//
	// base hadolint container
	// It need contain hadolint
	//
	BaseHadolintContainer *Container // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/main.go#L40)
	//
	// The external build of container
	// Usefull when need build args
	//
	BuildContainer *Container // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/main.go#L45)
}

// A generated module for Image functions
//
// This module has been generated via dagger init and serves as a reference to
// basic module structure as you get started with Dagger.
//
// Two functions have been pre-created. You can modify, delete, or add to them,
// as needed. They demonstrate usage of arguments and return types using simple
// echo and grep commands. The functions can be called from the dagger CLI or
// from one of the SDKs.
//
// The first line in this comment block is a short description line and the
// rest is a long description with more detail on the module's purpose or usage,
// if appropriate. All modules should have a short description.
func (r *Query) Image(opts ...ImageOpts) *Image { // image (https://github.com/disaster37/dagger-library-go/tree/d7e755bbd544480c8a96adc2204d70cf40ee6c0c/image/main.go#L36)
	q := r.query.Select("image")
	for i := len(opts) - 1; i >= 0; i-- {
		// `baseHadolintContainer` optional argument
		if !querybuilder.IsZeroValue(opts[i].BaseHadolintContainer) {
			q = q.Arg("baseHadolintContainer", opts[i].BaseHadolintContainer)
		}
		// `buildContainer` optional argument
		if !querybuilder.IsZeroValue(opts[i].BuildContainer) {
			q = q.Arg("buildContainer", opts[i].BuildContainer)
		}
	}

	return &Image{
		query: q,
	}
}
