server:
  enabled: true
  replicas: 1
  image:
    repository: ghcr.io/webcenter-fr/gohookbridge
    tag: main
    pullPolicy: IfNotPresent
  port: 3333
  publicURL: ""
  raftDir: /data/raft
  resources: {}
  ingress:
    enabled: false
    className: ""
    hosts: []
    tls: []
  service:
    type: ClusterIP
    port: 3333

client:
  enabled: false
  replicas: 1
  image:
    repository: ghcr.io/webcenter-fr/gohookbridge
    tag: main
    pullPolicy: IfNotPresent
  channelURL: ""
  targetURL: ""
  encryptionKeyFile: ""
  resources: {}

proxy:
  enabled: false
  replicas: 1
  image:
    repository: ghcr.io/webcenter-fr/gohookbridge
    tag: main
    pullPolicy: IfNotPresent
  listenPort: 9090
  targetURL: ""
  publicKey: ""
  resources: {}

encryption:
  createSecret: false
  publicKey: ""
  privateKey: ""
  existingSecret: ""

serviceAccount:
  create: false
  name: ""

nameOverride: ""
fullnameOverride: ""