# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gohookbridge < Formula
  desc "gohookbridge - A webhook and https://smee.io forwarder"
  homepage "https://github.com/webcenter-fr/gohookbridge"
  version "0.0.1"

  on_macos do
    url "https://github.com/webcenter-fr/gohookbridge/releases/download/0.0.1/gohookbridge_0.0.1_darwin_all.tar.gz"
    sha256 "d5b29f3dedfba8a3d0b50510ecaa70461e6304092cf0cc64365a46694fffbbb2"

    define_method(:install) do
      bin.install "gohookbridge" => "gohookbridge"
      output = Utils.popen_read("SHELL=bash #{bin}/gohookbridge completion bash")
      (bash_completion/"gohookbridge").write output
      output = Utils.popen_read("SHELL=zsh #{bin}/gohookbridge completion zsh")
      (zsh_completion/"_gohookbridge").write output
      output = Utils.popen_read("SHELL=zsh #{bin}/gohookbridge completion fish")
      (fish_completion/"gohookbridge.fish").write output
      prefix.install_metafiles
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/webcenter-fr/gohookbridge/releases/download/0.0.1/gohookbridge_0.0.1_linux_x86_64.tar.gz"
      sha256 "2a542760fa0e93e15ad2de0878f5fa8f0e4bfa0aabfba770dc39763b0f309df9"
      define_method(:install) do
        bin.install "gohookbridge" => "gohookbridge"
        output = Utils.popen_read("SHELL=bash #{bin}/gohookbridge completion bash")
        (bash_completion/"gohookbridge").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/gohookbridge completion zsh")
        (zsh_completion/"_gohookbridge").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/gohookbridge completion fish")
        (fish_completion/"gohookbridge.fish").write output
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/webcenter-fr/gohookbridge/releases/download/0.0.1/gohookbridge_0.0.1_linux_arm64.tar.gz"
      sha256 "e217c06cd0a4092484ffcceb3d25e37e51b3936334de54c5eded027198a6405e"
      define_method(:install) do
        bin.install "gohookbridge" => "gohookbridge"
        output = Utils.popen_read("SHELL=bash #{bin}/gohookbridge completion bash")
        (bash_completion/"gohookbridge").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/gohookbridge completion zsh")
        (zsh_completion/"_gohookbridge").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/gohookbridge completion fish")
        (fish_completion/"gohookbridge.fish").write output
        prefix.install_metafiles
      end
    end
  end
end
