# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gohookbridge < Formula
  desc "gohookbridge - A webhook and https://smee.io forwarder"
  homepage "https://github.com/webcenter-fr/gohookbridge"
  version "0.0.1"

  on_macos do
    url "https://github.com/webcenter-fr/gohookbridge/releases/download/0.0.1/gohookbridge_0.0.1_darwin_all.tar.gz"
    sha256 "f545dd55e67b3da80a96df64e8cc1c4b5d9546d8cbd7ab432bfb6245574babc6"

    define_method(:install) do
      bin.install "gohookbridge" => "gohookbridge"
      output = Utils.popen_read("SHELL=bash #{bin}/gohookbridge completion bash")
      (bash_completion/"gohookbridge").write output
      output = Utils.popen_read("SHELL=zsh #{bin}/gohookbridge completion zsh")
      (zsh_completion/"_gohookbridge").write output
      output = Utils.popen_read("SHELL=zsh #{bin}/gohookbridge completion fish")
      (fish_completion/"gohookbridge.fish").write output
      prefix.install_metafiles
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/webcenter-fr/gohookbridge/releases/download/0.0.1/gohookbridge_0.0.1_linux_x86_64.tar.gz"
      sha256 "adf8848650eccb5226a8db9001f6ace1b469c6c9fdbf3cc445cecb84dbed2c7f"
      define_method(:install) do
        bin.install "gohookbridge" => "gohookbridge"
        output = Utils.popen_read("SHELL=bash #{bin}/gohookbridge completion bash")
        (bash_completion/"gohookbridge").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/gohookbridge completion zsh")
        (zsh_completion/"_gohookbridge").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/gohookbridge completion fish")
        (fish_completion/"gohookbridge.fish").write output
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/webcenter-fr/gohookbridge/releases/download/0.0.1/gohookbridge_0.0.1_linux_arm64.tar.gz"
      sha256 "00d5143944348e202967b0cf71c2d807d1be939517552e2ca43d82c21016386f"
      define_method(:install) do
        bin.install "gohookbridge" => "gohookbridge"
        output = Utils.popen_read("SHELL=bash #{bin}/gohookbridge completion bash")
        (bash_completion/"gohookbridge").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/gohookbridge completion zsh")
        (zsh_completion/"_gohookbridge").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/gohookbridge completion fish")
        (fish_completion/"gohookbridge.fish").write output
        prefix.install_metafiles
      end
    end
  end
end
